version: 0.2

env:
  shell: bash
  parameter-store:
    GIT_USER: "/CodeBuild/Git_USER"
    GIT_PASS: "/CodeBuild/Git_PASS"

phases:
  install:
    commands:
      - echo Executing install phase
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - org_name=$(echo $CODEBUILD_SOURCE_REPO_URL | awk '{split($0,org,"/"); print org[4]}')
      - echo $org_name
      - echo $CODEBUILD_SOURCE_VERSION

      - echo $CODEBUILD_WEBHOOK_MERGE_COMMIT
      - echo $CODEBUILD_WEBHOOK_PREV_COMMIT
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF

      # Codebuild only runs on PUSH events if HEAD_REF
      # is refs/heads/develop (merge to develop). In this
      # case CODEBUILD_GIT_BRANCH="develop"

      - if [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" ];
        then export CODEBUILD_GIT_BRANCH="develop";
        echo "Merging to develop";
        else export CODEBUILD_GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/};
        fi

      # Determine the git base branch. This is the branch we are merging into.
      # It can be develop or another branch. It will be used as a fall back branch in clone.sh
      - export GIT_BASE_BRANCH=${CODEBUILD_WEBHOOK_BASE_REF#refs/heads/}

      - echo "GIT_BASE_BRANCH=${GIT_BASE_BRANCH}"
      - echo "CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH}"
      - echo "CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}"

      # read cdash url from s3
      - wget https://ci-test-cdash-url.s3.amazonaws.com/cdash_url.txt
      - CDASH_URL=$(cat cdash_url.txt)

  pre_build:
    commands:
      - echo Executing pre_build phase
      - mkdir -p /jcsda/ufo-bundle

      # Upload branch name and commit sha as CodeBuild artifact to S3
      - mkdir -p /jcsda/artifacts
      - echo ${CODEBUILD_GIT_BRANCH} > /jcsda/artifacts/branch_name.txt
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} > /jcsda/artifacts/commit_sha.txt

      - cd CI

      #  Setting git credentials
      - git lfs install # creates .gitconfig
      - sed -i '/ssh/d' ~/.gitconfig
      - sed '/instead/d' ~/.gitconfig
      - git config --global credential.helper store
      - touch ~/.git-credentials
      - chmod 0700 ~/.git-credentials
      - echo "https://${GIT_USER}:${GIT_PASS}@github.com" >~/.git-credentials

      # ufo
      - ./clone.sh jcsda-internal/ufo $CODEBUILD_GIT_BRANCH /jcsda/ufo-bundle ufo ${GIT_BASE_BRANCH} develop

      # ioda
      - ./clone.sh jcsda-internal/ioda $CODEBUILD_GIT_BRANCH  /jcsda/ufo-bundle ioda ${GIT_BASE_BRANCH} develop

      # saber
      - ./clone.sh jcsda-internal/saber $CODEBUILD_GIT_BRANCH /jcsda/ufo-bundle saber ${GIT_BASE_BRANCH} develop

      # oops
      - ./clone.sh jcsda-internal/oops $CODEBUILD_GIT_BRANCH  /jcsda/ufo-bundle oops ${GIT_BASE_BRANCH} develop

      # crtm
      - ./clone.sh jcsda/crtmv3 $CODEBUILD_GIT_BRANCH /jcsda/ufo-bundle crtm ${GIT_BASE_BRANCH} develop

      # rttov
      - ./clone.sh jcsda-internal/rttov $CODEBUILD_GIT_BRANCH /jcsda/ufo-bundle rttov ${GIT_BASE_BRANCH} develop

      # ropp
      - ./clone.sh jcsda-internal/ropp-test $CODEBUILD_GIT_BRANCH /jcsda/ufo-bundle ropp-ufo ${GIT_BASE_BRANCH} develop

      # gsw
      - ./clone.sh jcsda-internal/GSW-Fortran $CODEBUILD_GIT_BRANCH /jcsda/ufo-bundle gsw ${GIT_BASE_BRANCH} develop

      # ufo-test
      - ./clone.sh jcsda-internal/ufo-data $CODEBUILD_GIT_BRANCH /jcsda/ufo-bundle ufo-data ${GIT_BASE_BRANCH} develop

      # oasim
      - ./clone.sh jcsda-internal/oasim $CODEBUILD_GIT_BRANCH /jcsda/ufo-bundle oasim ${GIT_BASE_BRANCH} develop

      # move CMakeLists.txt
      - cp CMakeLists.txt /jcsda/ufo-bundle
      - cp -r cmake /jcsda/ufo-bundle/
      # cdash upload setup
      - cp /jcsda/ufo-bundle/cmake/CTestConfig.cmake /jcsda/ufo-bundle
      - sed -i "s@CDASH_URL@$CDASH_URL@g" /jcsda/ufo-bundle/CTestConfig.cmake

      - chmod -R 777 /jcsda/ufo-bundle

      - cd /jcsda/ufo-bundle
      - ls

  build:
    on-failure: CONTINUE
    commands:
      - echo Executing build phase
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - export BUILD_STATUS="0"
      - echo $BUILD_STATUS

      - mkdir /build_container
      - chmod 777 /build_container

      # configure and build
      - cd /build_container
      - source /opt/spack-environment/activate.sh
      - ecbuild -Wno-dev -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCDASH_OVERRIDE_SITE=CodeBuild -DCDASH_OVERRIDE_SYSTEM_NAME=ClangContainer -DUFO_TEST_TIER=2 -DCDASH_OVERRIDE_GIT_BRANCH=$CODEBUILD_GIT_BRANCH -DCTEST_UPDATE_VERSION_ONLY=FALSE /jcsda/ufo-bundle


      - cd /build_container/ufo
      - cp ../DartConfiguration.tcl .
      - sed -i 's/ufo-bundle/ufo-bundle\/ufo/' DartConfiguration.tcl
      - sed -i 's/build_container/build_container\/ufo/' DartConfiguration.tcl
      - cat DartConfiguration.tcl
      - make -j4

      - echo $CODEBUILD_BUILD_SUCCEEDING
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ];
        then export BUILD_STATUS="1";
        echo "Build passed";
        fi
      - echo $BUILD_STATUS

      # run ctest
      - cd /build_container/ufo
      - ctest -C RelWithDebInfo -D ExperimentalTest

    finally:
      - cd /build_container/ufo
      - ctest -C RelWithDebInfo -D ExperimentalSubmit -M Continuous -- --track Continuous --group Continuous

  post_build:
    commands:
      - echo Executing post_build phase
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo $BUILD_STATUS

      # upload find cdash url and upload it as CodeBuild artifact to S3
      - if [ "$BUILD_STATUS" = "1" ];
        then echo "Build & tests passed, find cdash url";
        url=$(bash /jcsda/ufo-bundle/ufo/CI/cdash-url.sh /build_container/ufo/Testing $CDASH_URL);
        echo $url;
        echo ${url} > /jcsda/artifacts/cdash-url.txt;
        cat /jcsda/artifacts/cdash-url.txt;
        else echo "Build failed";
        fi

artifacts:
  files:
    - '/jcsda/artifacts/*'
  name: ufo-clang-url
