#pragma once

// This file defines what appears on the Main Page of the documentation
// generated by doxygen. The file contains no code, and does not appear
// in any cpp include statement.
//
/*!
 * \mainpage Unified Forward Operator (UFO)
 *
 * UFO provides the observational operators needed to compute departures and innovations. In other words, it enables the comparison between model forecasts and observations that lies at the heart of the data assimilation process. UFO also provides related functionality related to observations such as quality control (QC) filters and variational bias correction.
 *
  */
