---
name: UKMO Integration Test

on:
  pull_request:
    branches: [develop]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install linter
        run: |
          python3 -m pip install fortitude-lint
      - name: Run fortitude check
        run: |
          fortitude check

  build:
    if: |
      ( github.repository_owner == 'JCSDA-internal' && github.event.pull_request.draft == false )
    name: gnu-openmpi
    runs-on: jedi-self-hosted-ext
    env:
      NAMESPACE: pr-${{ github.event.number }}
      MOBB_CI_PR_BODY_OUT: mobb-ci-gh-pr-${{ github.event.number }}-body.out
      REPO: ${{ github.event.repository.name }}
      REPO_TEST_DATA: ${{ github.event.repository.name }}-data
      TIMEOUT_MINUTE: 301

    steps:
      - name: Cleanup (pre)
        run: |
          rm -fr "./${NAMESPACE}" "./${MOBB_CI_PR_BODY_OUT}"

      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: ./${{ env.NAMESPACE }}

      - name: Set CI variables
        run: |
          gh pr view --json 'body' --jq '.body' --repo "${GITHUB_REPOSITORY}" \
            "${GITHUB_HEAD_REF}" >"./${MOBB_CI_PR_BODY_OUT}"
          image_tag="${GITHUB_BASE_REF##*/}"
          declare -A settings
          settings['MOBB_CI_IMAGE_TAG']="${image_tag}"
          settings['MOBB_CI_TEST_TIER']='1'
          for name in "${!settings[@]}"; do
            default="${settings[${name}]}"
            value="$( \
              sed -n \
              -e 's/^[[:space:]]*'"${name}"'=\([^[:space:]]\+\).*$/\1/p' \
              "./${MOBB_CI_PR_BODY_OUT}")"
            value="${value:-${default}}"
            echo "${name}=${value}"
          done >>"${GITHUB_ENV}"

      - name: Run
        run: |
          docker run --rm \
            --name "${REPO}-${NAMESPACE}-${GITHUB_SHA::7}" \
            --volume "./${MOBB_CI_PR_BODY_OUT}:/var/tmp/${MOBB_CI_PR_BODY_OUT}" \
            --volume "./${NAMESPACE}:/var/tmp/mobb-ci-${NAMESPACE}" \
            --volume '/testdata/mobb-data:/var/tmp/mobb-data' \
            --env GH_TOKEN="${{ secrets.GH_PAT }}" \
            --env GITHUB_HEAD_REF="${GITHUB_HEAD_REF}" \
            --env GITHUB_REPOSITORY="${GITHUB_REPOSITORY}" \
            --env MOBB_CI_PR_BODY_OUT="/var/tmp/${MOBB_CI_PR_BODY_OUT}" \
            --env MOBB_CI_TEST_TIER="${MOBB_CI_TEST_TIER}" \
            --env MOBB_DATA='/var/tmp/mobb-data' \
            --env REPO="${REPO}" \
            --env REPO_TEST_DATA="${REPO_TEST_DATA}" \
            --entrypoint '/usr/bin/env' \
            --workdir="/var/tmp/mobb-ci-${NAMESPACE}" \
            "ngmssboxjediacr.azurecr.io/jedibase:${MOBB_CI_IMAGE_TAG}" \
            'timeout' "$((TIMEOUT_MINUTE - 1))m" '/usr/local/bin/mobb-ci'
        timeout-minutes: ${{ fromJSON(env.TIMEOUT_MINUTE) }}

      - name: Cleanup (post)
        run: rm -fr "./${NAMESPACE}" "./${MOBB_CI_PR_BODY_OUT}"
